spring:
  application:
    name: backend

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    resources:
      static-locations: file:uploads/

  mvc:
    static-path-pattern: /uploads/**

server:
  port: 8080

otp:
  demo-mode: true   # ❌ CHANGE IN PROD
  expiration-seconds: 130

mpis:
  ai:
    confident-threshold: 0.75
    review-threshold: 0.60
    required-frames: 1
    engine-url: ${MPIS_AI_ENGINE_URL}

  cache:
    dedup-window-seconds: 10
    tracker-window-seconds: 3

  jwt:
    secret: ${JWT_SECRET}   # 🔥 NEVER hardcode
    expiration-ms: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: ALWAYS

    prometheus:
      enabled: true